model-settings:
  #prediction-threshold: 0.23 #minimum confidence (0 to 1) (confiança mínima (0 a 1))
  prediction-threshold: 0.225 #CALIBRATED THRESHOLD
  model-name: 'ViT-B/32'
  device: 'cpu' #switch to 'cuda' if you have GPU (troque para 'cuda' se tiver GPU)

##If there are many false positives: increase to 0.23
##If there are many false negatives: decrease to 0.22

label-settings:
  labels:
    - "Violence: physical fighting, punches, kicks, assault, aggression, brawl, armed conflict, weapon attack, knife attack, gun violence, person holding a knife, person with a weapon, violent struggle, dangerous altercation"
    - "Non-violence: calm, peaceful, normal activity, people talking, safe, neutral, everyday scene, harmless situation, friendly interaction, relaxed atmosphere"
  default-label: "Non-violence: normal scene, no physical aggression, people talking calmly, safe environment"
